<?php

/*
 * The public site is static HTML generated by `php artisan site:build` and
 * served directly by the web server, so there are no web routes. The admin
 * dashboard and API live under /api.
 */
